### PR TITLE
First iteration on ErrorStreams

### PR DESCRIPTION
**Pull request by kaifox**
Dear All,

this is a first version of a proposal how to deal with errors in long-living streams: The principle idea for the moment is that factories always create pairs of streams: one with the data and a second one with errors. Both are registered in the pool. 
In case the factory does not want to create an explicit error stream, then she can create a  Stream.ofData(Publisher) and the error stream which will be registered will be Flowable.never().

It seems to be good practise to always register an error stream, because otherwise automatic tools (e.g. reacting on hooks) would have problems...

When providing a stream, currrently no error stream is created though ... not sure if this makes sense ... we have no control there anyhow...

Not all factories follow the contract yet. I implemented two cases: DerivedStreamFactory and FilteredStreamId. So please have a look there to get an idea of the principle.

There are some otheres which might be much more tricky to get safe.

I think a next step should be to move the ComposableStreamId to another project, since this one is uncontrollable (is it used somewhere)?

Let me know what you think....

Kajetan

### CODE REVIEW

**Comment by andreacalia** [comment]
Hi!

As we discussed, I think this is a good approach 👍 
As soon as we have a sprint for streamingpool we should include this feature.

@makemeunsee @michi42 what is your opinion?

Cheers,
Andrea

**Comment by michi42** [comment]
Fine for me. It 'feels' like a hack, but it is probably the best we can do within the current API framework of reactive streams.

**Comment by kaifox** [comment]
Yes indeed it feels a bit like a hack ... probably we find something better at some time ... 
I think I still would do some more renaming before we merge, but nothing too big....

**Comment by andreacalia** [comment]
Maybe we can use empty() instrad of notCreated.. anyway I don't think we can do much better with failfast reactive streams.. :)

**Pull request merged**
